// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAti5Z4xScEDKF8sxM8QSXPwQkr9YJNuAk',
    appId: '1:507019505897:web:eba62780ecbcbfc4a70078',
    messagingSenderId: '507019505897',
    projectId: 'expense-537cc',
    authDomain: 'expense-537cc.firebaseapp.com',
    storageBucket: 'expense-537cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCTAJfAyPVWzoohKJiew41Cc7JbMSUGk',
    appId: '1:507019505897:android:5ca3d99ac1704188a70078',
    messagingSenderId: '507019505897',
    projectId: 'expense-537cc',
    storageBucket: 'expense-537cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9TOovibdKd77c7GFvAc55Kf_NgukO2Rs',
    appId: '1:507019505897:ios:b9dd87433a6f4eeda70078',
    messagingSenderId: '507019505897',
    projectId: 'expense-537cc',
    storageBucket: 'expense-537cc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAti5Z4xScEDKF8sxM8QSXPwQkr9YJNuAk',
    appId: '1:507019505897:web:9dccddb5242ccebba70078',
    messagingSenderId: '507019505897',
    projectId: 'expense-537cc',
    authDomain: 'expense-537cc.firebaseapp.com',
    storageBucket: 'expense-537cc.firebasestorage.app',
  );
}
